### PR TITLE
Revert "Create wholenewfile"

### PR DESCRIPTION
**Pull request by marco-c0d3**
Reverts Writers-Instagram/play-bucket#17

### CODE REVIEW

**Comment by derberg** [comment]
Congratulations. You've managed to get merge conflict that cannot be solved in GitHub UI. Never happened to me over last 3 years :)
Let me know if you want to take this further and you need my support

**Comment by marco-c0d3** [comment]
Hey Lukasz,

I don't really get what you're saying. Totally new to GitHub. I was in 
your workshop at Tekom and just followed your instructions. But maybe I 
did anything wrong?

Greets,

Marco


Am 27.10.2017 um 08:52 schrieb Lukasz Gornicki:

**Comment by derberg** [comment]
Not a problem, I'm here to help you our to start if you want. It is totally up to you. Do you want to take this pull request further and just close it without any further action?

**Comment by marco-c0d3** [comment]
I think I'd just like to close it...


Am 27.10.2017 um 16:42 schrieb Lukasz Gornicki:

**Pull request closed without merging**
